//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycybergames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string ID_KhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaNhap { get; set; }
        public string LoaiKhachHang { get; set; }
        public string ID_ThanhVien { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
