//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycybergames.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiTaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiTaiKhoan()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
        [Display(Name = "ID Loại Tài Khoản")]
        [Required(ErrorMessage = "ID loại tài khoản không được để trống")]
        public string ID_LoaiTK { get; set; }

        [Display(Name = "Tên Loại Tài Khoản")]
        [Required(ErrorMessage = "Tên loại tài khoản không được để trống")]
        public string TenLoaiTK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
