//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycybergams.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public string ID_KhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaNhap { get; set; }
        public string LoaiKhachHang { get; set; }
        public string TenDN { get; set; }
        public string Matkhau { get; set; }
        public Nullable<decimal> GiaMay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
