//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycycybergames.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
        [Display(Name = "Mã dịch vụ")]
        public string ID_DV { get; set; }
        [Display(Name = "Tên dịch vụ")]
        public string TenDV { get; set; }
        [Display(Name = "Ảnh sản phẩm")]
        public string AnhSP { get; set; }
        [Display(Name = "Giá bán")]
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mã mặt hàng")]
        public string ID_Mathang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
